Major BeanScene ReservationSystem/Controllers/MVC Controllers/MenuController.cs
using Microsoft.AspNetCore.Mvc;
using MongoDbOrdersAPI.Services;

namespace Major_BeanScene_ReservationSystem.Controllers.MVC_Controllers
{
    public class MenuController : Controller
    {
        private readonly MenuItemService _menuItemService;
        public MenuController(MenuItemService menuItemService)
        {
             _menuItemService = menuItemService;
        }
        public IActionResult Index()
        {
            var menuItems = _menuItemService.GetAsync().Result;


            return View(menuItems);
        }
    }
}

Major BeanScene ReservationSystem/Controllers/MVC Controllers/ReservationController.cs
using Major_BeanScene_ReservationSystem.CustomValidation;
using Major_BeanScene_ReservationSystem.Data;
using Major_BeanScene_ReservationSystem.Data.Models;
using Major_BeanScene_ReservationSystem.Models.Reservation;
using Mapster;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Major_BeanScene_ReservationSystem.Controllers
{
    public class ReservationController : Controller
    {
        protected readonly ApplicationDbContext _context;
        protected readonly UserManager<IdentityUser> _userManager;
        protected readonly SignInManager<IdentityUser> _signInManager;
        public ReservationController(ApplicationDbContext context, UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager)
        {
            _context = context;
            _userManager = userManager;
            _signInManager = signInManager;
        }

        [HttpGet]
        public IActionResult Create()
        {

            DateTime dateTime = new(DateTime.Now.Year, DateTime.Now.Month, DateTime.Now.Day, DateTime.Now.Hour, DateTime.Now.Minute, 0);
            
            var p = _context.People.FirstOrDefault(p => p.Email == User.Identity.Name);
            if(p != null)
            {                
                var m = new CreateWithSelectedDate
                {
                    ForSomeoneElse = null,
                    FirstName = p.FirstName,
                    LastName = p.LastName,
                    Email = p.Email,
                    SelectedDate = dateTime.Date
                };

                return View(m);
            }
            else if (_signInManager.IsSignedIn(User))
            {
                var m = new CreateWithSelectedDate
                {
                    ForSomeoneElse = null,
                    Email = User.Identity.Name,
                    SelectedDate = dateTime.Date
                };

                return View(m);
            }
            else
            {
                var m = new CreateWithSelectedDate
                {
                    ForSomeoneElse = null,
                    SelectedDate = dateTime.Date
                    //StartTime = dateTime.AddHours(1)
                };

                return View(m);
            }
        }
        [HttpPost]
        public IActionResult UpdateCreateModel([Bind("SelectedDate")][FromBody]Update m)
        {
            //later on validate the selected date to only future dates
            if (ModelState.IsValid) {
                var model = new Models.Reservation.Create()
                {
                    Sitting = new SelectList(_context.Sittings.Where(x => x.StartTime <= m.SelectedDate
                    & x.EndTime >= m.SelectedDate & x.IsClosed != true), "Id", "Name"),
                };
                return Ok(new { SittingId = model.Sitting });

            }
            else
            {
                return BadRequest(new { message = "Invalid date format"});
            }
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateWithSelectedDate m)
        {
            var personExist = await _context.People.FirstOrDefaultAsync(p => p.Email == m.Email);
            var u = await _context.Users.FirstOrDefaultAsync(u => u.Email == m.Email);

            if (ModelState.IsValid)
            {
                var r = m.Adapt<Reservation>();

                if (m.ForSomeoneElse == true)
                {
                    if (m.GuestPhoneNumber == null)
                    {
                        ModelState.AddModelError("GuestPhoneNumber", "Guest phone number is required when making a reservation for someone else.");
                    }
                    
                    var g = m.Adapt<Guest>();
                    g.FirstName = m.GuestFirstName;
                    g.LastName = m.GuestLastName;
                    g.Email = m.GuestEmail;
                    g.PhoneNumber = m.GuestPhoneNumber;

                    _context.Add(g);
                    await _context.SaveChangesAsync();
                    if (personExist != null)
                    {
                        r.Guest = g;
                        r.GuestId = g.Id;
                        r.Person = personExist;
                        r.ReservationOriginId = 1;
                        r.Guests = m.NumberOfGuests;
                        r.StartTime = m.SelectedDate + m.SelectedTime;
                        _context.Add(r);

                        await _context.SaveChangesAsync();
                    }
                    else
                    {
                        var p = m.Adapt<Person>();
                        _context.People.Add(p);
                        r.GuestId = g.Id;
                        r.Guest = g;
                        r.Person = p;
                        r.ReservationOriginId = 1;
                        r.Guests = m.NumberOfGuests;
                        r.StartTime = m.SelectedDate + m.SelectedTime;
                        _context.Add(r);

                        await _context.SaveChangesAsync();
                    }

                    return RedirectToAction("Confirmation", new { id = r.Id });
                }
                else
                {     
                    if (u != null && personExist != null)
                    {
                        personExist.UserId= u.Id;

                        r.Person = personExist;
                        r.ReservationOriginId = 1;
                        r.Guests = m.NumberOfGuests;
                        r.StartTime = m.SelectedDate + m.SelectedTime;
                        _context.Add(r);

                        await _context.SaveChangesAsync();
                    }
                    else if (personExist != null)
                    {
                        r.Person = personExist;
                        r.ReservationOriginId = 1;
                        r.Guests = m.NumberOfGuests;
                        r.StartTime = m.SelectedDate + m.SelectedTime;
                        _context.Add(r);

                        await _context.SaveChangesAsync();
                    }
                    else
                    {
                        var p = m.Adapt<Person>();
                        _context.People.Add(p);

                        r.Person = p;
                        r.ReservationOriginId = 1;
                        r.Guests = m.NumberOfGuests;
                        r.StartTime = m.SelectedDate + m.SelectedTime;
                        _context.Add(r);

                        await _context.SaveChangesAsync();
                    }

                    return RedirectToAction("Confirmation", new { id = r.Id });
                }
            }
            
            m.Sitting = new SelectList(_context.Sittings, "Id", "Name");
            return View(m);
        }

        [HttpGet]
        public IActionResult Confirmation(int id)
        {
            var reservation = _context.Reservations
            .Include(r => r.Person)
            .Include(r => r.Guest)
            .Include(r => r.ReservationOrigin)
            .Include(r => r.ReservationStatus)
            .FirstOrDefault(r => r.Id == id);

            if (reservation == null)
            {
                return NotFound();
            }

            return View(reservation);
        }

        public IActionResult ValidateDate([Bind("SelectedDate")]DateTime selectedDate)
        {

            if (selectedDate == null)
            {
                return Json(false);
            }
            if (selectedDate < DateTime.Now.Date)
            {
                return Json("You cannot make a reservation for a date that has passed. Please select a future date.");
            }

            return Json(true);
        }

        public IActionResult ValidateGuests([Bind("NumberOfGuests")]int numberOfGuests)
         {
            if (numberOfGuests == null)
            {
                return Json(false);
            }
            if (numberOfGuests > 10)
            {
                return Json("Maximum 10 guests allowed. Please contact us for larger groups.");
            }
            else if (numberOfGuests <= 0)
            {
                return (Json("There must be at least 1 guest to make a reservation."));
            }

            return Json(true);
        }

        public IActionResult ValidateTime([Bind("SelectedTime", "SelectedDate")] TimeSpan selectedTime, int sittingId, DateTime selectedDate)
        {
            var selectedSitting = _context.Sittings.FirstOrDefault(s => s.Id == sittingId);

            if (selectedSitting == null || selectedTime == null)
            {
                return Json(false);
            }

            if (selectedSitting.StartTime.Date != selectedSitting.EndTime.Date)
            {
                // Handle overnight reservations
                var midnight = new TimeSpan(0, 0, 0);
                var quarterToMidnight = new TimeSpan(23, 45, 0);
                if (selectedDate.Date == selectedSitting.StartTime.Date && selectedTime < selectedSitting.StartTime.TimeOfDay)
                {
                    return Json("Invalid time selection. Please choose a time within the sitting's duration.");
                }
                if(selectedDate.Date == selectedSitting.EndTime.Date && selectedTime > selectedSitting.EndTime.TimeOfDay)
                {
                    return Json("Invalid time selection. Please choose a time within the sitting's duration.");
                }

                if(selectedDate.Date == DateTime.Now.Date && selectedTime < DateTime.Now.TimeOfDay)
                {
                    return Json("You cannot book reservations for a time that has passed. Please select a future time.");
                }

Major BeanScene ReservationSystem/Views/Shared/_CreateReservation.cshtml
@model Major_BeanScene_ReservationSystem.Models.Reservation.Create

@{
    ViewData["Title"] = "Create";
}

<h1>Make a Reservation!</h1>

<p>Create an Account? | <a asp-area="Identity" asp-page="/Account/Register">Register</a></p>
<p>Already a Member? | <a asp-area="Identity" asp-page="/Account/Login">Login</a></p>

<div class="row">
    <div class="col-md-4">
        <form id="reservationForm" asp-action="Create" method="post" autocomplete="off">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" placeholder="e.g. John" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" placeholder="e.g. Smith" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" placeholder="e.g. john@example.com" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SittingId" class="control-label"></label>
                <select asp-for="SittingId" class="form-control" asp-items="Model.Sitting">
                    <option value="">-- Please Select a Sitting --</option>
                </select>
                <span asp-validation-for="SittingId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartTime" class="control-label"></label>
                <input asp-for="StartTime" class="form-control" />
                @* <input asp-for="StartTime" class="form-control" min="@DateTime.Now.ToString("yyyy-MM-ddThh:mm")" /> *@
                <span asp-validation-for="StartTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Duration" class="control-label"></label>
                <input asp-for="Duration" class="form-control" placeholder="Length of your reservation in minutes" />
                <span asp-validation-for="Duration" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumberOfGuests" class="control-label"></label>
                <select id="numGuests" asp-for="NumberOfGuests" asp-items="@(new SelectList(Enumerable.Range(1, 10)))" class="form-control">
                    <option value="">--Select the number of guests--</option>
                </select>
                <span asp-validation-for="NumberOfGuests" class="text-danger"></span>
                <span id="guestsValidationError" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AdditionalNotes" class="control-label"></label>
                <textarea asp-for="AdditionalNotes" class="form-control"></textarea>
                <span asp-validation-for="AdditionalNotes" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Home" asp-action="Index">Back to Home</a>
</div>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

    <script>
        document.getElementById("reservationForm").addEventListener("submit", function (event) {
            const numGuests = document.getElementById("numGuests").value;
            const guestsValidationError = document.getElementById("guestsValidationError");

            if (numGuests > 10) {
                guestsValidationError.textContent = "Maximum 10 guests allowed. Please contact us for larger groups.";
                event.preventDefault();
            } else {
                guestsValidationError.textContent = "";
            }
        });


        $(document).ready(function () {
            $('#StartTime').on('change', function () {
                var selectedDate = $(this).val();
                let data = { "selectedDate": selectedDate }
                fetch('/Reservation/UpdateCreateModel', {
                    method: "POST",
                    headers: { "Content-Type": "application/json" },
                    body: JSON.stringify(data)
                })
                    .then(response => response.json())
                    .then(data => {
                        $('#SittingId').empty();
                        if (data.sittingId.length === 0) {
                            $('#SittingId').append($("<option/>").attr('value', '').text("No available sittings"));
                        } else {
                            $('#SittingId').append($("<option/>").attr('value', '').text(`${data.sittingId.length} available sittings`));
                            $.each(data.sittingId, function (index, item) {
                                $('#SittingId').append($("<option />").attr('value', item.value).text(item.text));
                            });
                        }
                    })
                    .catch(console.log("Error"))
                // $.ajax({
                //     type: 'POST',
                //     url: '/Reservation/UpdateCreateModel',
                //     data: { selectedDate: selectedDate },
                //     success: function (data) {
                //         // Update the model
                //         $('#SittingId').empty();
                //         if (data.sittingId.length === 0) {
                //             $('#SittingId').append($("<option/>").attr('value','').text("No available sittings"));
                //         }
                //         else {
                //             $('#SittingId').append($("<option/>").attr('value', '').text(`${data.sittingId.length} available sittings`));
                //             $.each(data.sittingId, function (index, item) {
                //                 $('#SittingId').append($("<option />").attr('value', item.value).text(item.text));
                //             });
                //         }


                //     },
                //     error: function (xhr, status, error) {
                //         // Handle errors (if any)
                //         console.log('Error:', error);
                //     }
                // });
            });
        });

    </script>
}

Major BeanScene ReservationSystem/Views/Shared/_ErrorMessage.cshtml
<div class="bg-danger  rounded-pill ">
    <div class="alert alert-damger alert-dismissible fade show" role="alert">
        @TempData["Error"]
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
</div>

Major BeanScene ReservationSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Major_BeanScene_ReservationSystem</title>
    @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />*@
    <link rel="stylesheet" href="~/lib/twitter-bootstrap/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Major_BeanScene_ReservationSystem.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/navStyling.css" />
    <link rel="stylesheet" href="~/css/footerAndHeaderForLayouts.css" />
</head>

<body>
    <header class="bg-dark text-white">
        <nav class="navbar navbar-expand-sm">
            <div class="container-fluid">
                <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/images/BeanSceneLogo.png" alt="Bean Scene" width="50px" height="45px" /> Bean Scene</a>
                <button class="navbar-toggler bg-white" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li>
                            <a class="nav-link" asp-area="" asp-controller="Reservation" asp-action="Create">Reservations</a>
                        </li>
                        <li>
                            <a class="nav-link" asp-area="" asp-controller="Menu" asp-action="Index">Our Menu</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container body">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer text-center text-white bg-dark p-3 mt-4">
        <div class="container">
            &copy; 2023 - Bean Scene - Powered By Foie Gras @* <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a> *@
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    @*<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>*@
    <script src="~/lib/twitter-bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    
</body>
</html>

Major BeanScene ReservationSystem/Views/Shared/_SuccessMessage.cshtml
<div class="bg-success  rounded-pill ">
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        @TempData["Success"]
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
</div>