Major BeanScene ReservationSystem/Areas/Manager/Models/Employee/Create.cs
using System.ComponentModel.DataAnnotations;

namespace Major_BeanScene_ReservationSystem.Areas.Manager.Models.Employee
{
    public class Create
    {
        [Required]
        [EmailAddress]
        public string Email { get; set; }

        [Required]
        public string FirstName { get; set; }
        [Required]
        public string LastName { get; set; }

        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        //prevent admin from not existing
        //later use logging to record weird behavior
        public bool AssignAdminRole { get; set; }
    }
}

Major BeanScene ReservationSystem/Areas/Manager/Models/Sittings/Index.cs
using Major_BeanScene_ReservationSystem.Data.Models;

namespace Major_BeanScene_ReservationSystem.Areas.Manager.Models.Sittings
{
    public class Index
    {
        //private ICollection<Restaurant> _restaurants;
        //private ICollection<SittingType> sittingTypes;
        //public int Id { get; set; }
        //public int Capacity { get; set; }
        //public string Name { get; set; }
        //public bool IsClosed { get; set; }
        //public DateTime StartTime { get; set; }
        //public DateTime EndTime { get; set; }

    }
}

Major BeanScene ReservationSystem/Areas/Manager/Controllers/SittingsController.cs
using Major_BeanScene_ReservationSystem.Areas.Manager.Models.Sittings;
using Major_BeanScene_ReservationSystem.Data;
using Major_BeanScene_ReservationSystem.Data.Models;
using Major_BeanScene_ReservationSystem.Services;
using Mapster;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using static Major_BeanScene_ReservationSystem.Areas.Manager.Models.Sittings.Create;

namespace Major_BeanScene_ReservationSystem.Areas.Manager.Controllers
{
    public class SittingsController : ManagerBaseController
    {
        public SittingsController(ApplicationDbContext context) : base(context)
        {
        }

        public async Task<IActionResult> SearchSittings(int? pageNumber, int? pageSize, int? sittingTypeId, string sortOrder, string searchString, DateTime? selectedDate)
        {
            ViewData["CurrentSittingType"] = sittingTypeId;
            ViewData["CurrentPageSize"] = pageSize ?? 20;
            ViewData["CurrentSort"] = sortOrder;
            ViewData["CurrentFilter"] = searchString;
            ViewData["SelectedDate"] = selectedDate;
            ViewData["SittingStartTimeSortParm"] = String.IsNullOrEmpty(sortOrder) || sortOrder == "sittingStartTime" ? "sittingStartTime_desc" : "sittingStartTime";
            ViewData["SittingTypeSortParm"] = sortOrder == "sittingType" ? "sittingType_desc" : "sittingType";

            IQueryable<Sitting> queryable = _context.Sittings
                .Where(s => s.IsClosed == false || s.IsClosed == true)
                .Include(x => x.SittingType);

            if (sittingTypeId == null)
            {
                sittingTypeId = null;
                ViewData["CurrentSittingType"] = sittingTypeId;
            }

            if (sittingTypeId != null && sittingTypeId != 0)
            {
                queryable = queryable.Where(s => s.SittingTypeId == sittingTypeId);
            }

            if (selectedDate != null)
            {
                queryable = queryable.Where(s => s.StartTime.Date == selectedDate.Value.Date);
            }

            switch (sortOrder)
            {
                case "sittingStartTime_desc":
                    queryable = queryable.OrderByDescending(s => s.StartTime);
                    break;
                case "sittingStartTime":
                    queryable = queryable.OrderBy(s => s.StartTime);
                    break;
                case "sittingType_desc":
                    queryable = queryable.OrderByDescending(s => s.SittingType.Name);
                    break;
                case "sittingType":
                    queryable = queryable.OrderBy(s => s.SittingType.Name);
                    break;
                case "sittingName_desc":
                    queryable = queryable.OrderByDescending(s => s.Name);
                    break;
            }

            if (!String.IsNullOrEmpty(searchString))
            {
                queryable = queryable.Where(s => s.Name.Contains(searchString) || s.SittingType.Name.Contains(searchString));
            }

            SearchSittings model = new SearchSittings()
            {
                SittingType = new SelectList(await _context.SittingTypes.ToListAsync(), "Id", "Name"),
                Sittings = await PaginatedList<Sitting>.CreateAsync(queryable, pageNumber ?? 1, pageSize ?? 20),
                SelectedDate = selectedDate,
                SittingTypeId = sittingTypeId
            };

            return View(model);
        }


        // GET: Manager/Sittings
        public async Task<IActionResult> Index()
        {
            var model = await _context.Sittings
                        .Include(s => s.Restaurant)
                        .Include(s => s.SittingType)
                        .ToListAsync();

            LinkedList<Sitting> sittings = new LinkedList<Sitting>();
            foreach (var m in model)
            {
                sittings.AddLast(m);
            }

            return _context.Sittings != null ?
                        View(sittings) :
                        Problem("Entity set 'ApplicationDbContext.Sittings'  is null.");
        }

        // GET: Manager/Sittings/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Sittings == null)
            {
                return NotFound();
            }
            var sitting = await _context.Sittings
                .Include(s => s.Restaurant)
                .Include(s => s.SittingType)
                .Include(s => s.Reservations.Where(r => r.SittingId == id))
                    .ThenInclude(r => r.Tables)
                .Include(s => s.Reservations.Where(r => r.SittingId == id))
                    .ThenInclude(r => r.Person)
                .Include(s => s.Reservations.Where(r => r.SittingId == id))
                    .ThenInclude(r => r.Guest)
                .Include(s => s.Reservations.Where(r => r.SittingId == id))
                    .ThenInclude(r => r.ReservationOrigin)
                .Include(s => s.Reservations.Where(r => r.SittingId == id))
                    .ThenInclude(r => r.ReservationStatus)
                .FirstOrDefaultAsync(m => m.Id == id);
            var reservationOrigin = await _context.ReservationOrigins.ToListAsync();
            var reservationStatus = await _context.ReservationStatuses.ToListAsync();
            if (sitting == null)
            {
                return NotFound();
            }
            //Mapster notcrashing by changing Name

            var model = sitting.Adapt<Details>();
            model.ReservationsNotAdapted = sitting.Reservations;
            model.RestaurantNotAdapted = sitting.Restaurant;
            model.SittingTypeNotAdapted = sitting.SittingType;
            model.Reservation = new Details.UpdateReservation
            {
                
                ReservationOrigin = new SelectList(reservationOrigin, "Id", "Name"),
                ReservationStatus = new SelectList(reservationStatus, "Id", "Name")
            };

            return View(model);
        }
        [HttpGet]
        public IActionResult Create(DateTime? start,DateTime? end)
        {
            DateTime dateTime = new DateTime(DateTime.Now.Year,DateTime.Now.Month,DateTime.Now.Day,7,0,0);
            ////SelectList xx= new Se
            var model = new Create() {
                Capacity = 40,
                Restaurants = new SelectList(_context.Restaurants, "Id", "Name"),
                StartTime = dateTime,
                EndTime = dateTime.AddHours(2),
                SittingTypes = new SelectList(_context.SittingTypes, "Id", "Name"),
                SelectedDaysOfWeek = Enum.GetValues(typeof(DayOfWeek)).Cast<DayOfWeek>().ToList(),
                RepeatOptions =new List<SelectListItem>()
                {
                    new SelectListItem{Value = "1", Text="Never"},
                    new SelectListItem{Value = "2", Text="Daily"},
                    new SelectListItem{Value = "3", Text="Weekly"},
                }
            };
            if (start != null && end!=null)
            {
                model.StartTime = (DateTime)start;
                model.EndTime = (DateTime)end;
                TempData["Success"] =$"Sitting from {model.StartTime} to {model.EndTime}";
            }

            return View(model);
        }
        // POST: Manager/Sitting/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(
            [Bind("Capacity,Name,IsClosed,StartTime,EndTime,RestaurantId,SittingTypeId,RepeatOptionId,RepeatWeeksCount,SelectedDaysOfWeek,Occurence")] Create sitting)
        {
            if (ModelState.IsValid)
            {
                //No repeats
                if (sitting.RepeatOptionId == 1)
                {
                    var sit = sitting.Adapt<Sitting>();
                    _context.Add(sit);
                    await _context.SaveChangesAsync();
                    return RedirectToAction("Calendar", "Home", "");
                    //return RedirectToAction(nameof(Index));

                }
                //Repeat Daily
                if (sitting.RepeatOptionId == 2)
                {
                    if (sitting.Occurence ==0)
                    {
                        ModelState.AddModelError("Occurence","Must repeat at least one time");
                    }
                    else
                    {
                        //If repeat is 1, results in two sittings
                        
                        var sittings = new List<Sitting>();
                        for (int i = 0; i <= sitting.Occurence; i++)
                        {
                            var sit = sitting.Adapt<Sitting>();
                            sit.StartTime = sit.StartTime.AddDays(i * 7);
                            sit.EndTime = sit.EndTime.AddDays(i * 7);
                            
                            sittings.Add(sit);
                            
                        }
                        await _context.AddRangeAsync(sittings);
                        await _context.SaveChangesAsync();
                        //return RedirectToAction(nameof(Index));
                        return RedirectToAction("Calendar", "Home", "");
                    }
                    
                }
                if (sitting.RepeatOptionId == 3)
                {
                    //Allow for 1 week
                    if (sitting.Occurence == 0)
                    {
                        ModelState.AddModelError("Occurence", "Must repeat at least one time");
                    }
                    if (sitting.SelectedDaysOfWeek != null)
                    {

Major BeanScene ReservationSystem/Controllers/API Controllers/SittingsController.cs
using Microsoft.AspNetCore.Mvc;
using Major_BeanScene_ReservationSystem.Data.Models;
using Major_BeanScene_ReservationSystem.Data;
using MongoDB.Driver.Linq;
using Microsoft.EntityFrameworkCore;
using Mapster;

namespace Major_BeanScene_ReservationSystem.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class SittingsController : ControllerBase
    {
        private readonly ApplicationDbContext _context;

        public SittingsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: api/sittings
        [HttpGet]
        public ActionResult<IEnumerable<Sitting>> GetSittings()
        {
            var sittings = _context.Sittings.ToList();
            return Ok(sittings);
        }

        [HttpGet("{selectedDate}")]
        public ActionResult<IEnumerable<Sitting>> GetSittingsByDate(DateTime selectedDate)
        {
            // Retrieve sittings based on the specified date
            var availableSittings = _context.Sittings
                .Where(s =>
                selectedDate >= s.StartTime.Date &&
                selectedDate <= s.EndTime.Date
                && !s.IsClosed)
                .ToList();

            var sittingsToKeep = new List<Sitting>();

            foreach (var s in availableSittings)
            {
                if (s.EndTime >= DateTime.Now)
                {
                    sittingsToKeep.Add(s);
                }
            }

            return sittingsToKeep;
        }

        [HttpGet("getCurrentCapacity/{sittingId}")]
        public ActionResult GetCurrentCapacityOfSelectedSitting(int sittingId)
        {

            //Dynamic guest count based of the sitting, in Staff/Create/Reservation 
            //To do .. link it to staff/create/reservation
            var selectedSitting = _context.Sittings.Include("Reservations").FirstOrDefault(s=>s.Id== sittingId);
            if (selectedSitting == null)
            {
                return BadRequest("Could not find selected sitting");
            }
            return Ok(selectedSitting.CurrentCapacity);

        }
        [HttpGet("between")]
        public ActionResult<IEnumerable<Sitting>> GetAllSittingsWithinDateRangeCalander([FromQuery]DateTime start, [FromQuery]DateTime end)
        {
            // Retrieve sittings based on the specified date
            var sittings = _context.Sittings
                .Include(s=>s.Reservations)
                .Where(s =>
                s.StartTime >= start &&
                s.StartTime <= end)
                .Select(s=>
                new {title=s.Name +" Capacity: " +(s.Capacity-s.CurrentCapacity)+"/"+s.Capacity,
                    start=s.StartTime,
                    end=s.EndTime,
                    url=$"/manager/sittings/details/{s.Id}",

                })
                .ToList();

            return Ok(sittings);

        }


        //Geoffrey version
        //if you want to pass the dateTime (date&time) from c# to js and fetch into this api
        //1. In c#, Send this value as "dateTime.toString('s')" into the tag as data-attribute;
        // e.g. <span data-combined = "@u.dateTime.toString('s')" >
        //2. In js, Get the tag's data attribute, and use value for fetch
        [HttpGet("dateTime/{selectedDate}")]
        public ActionResult<IEnumerable<Sitting>> GetSittingsByDateMoreAccurate(DateTime selectedDate)
        {
            // Retrieve sittings based on the specified date
            var availableSittings = _context.Sittings
                .Where(s =>
                selectedDate.Date <= s.EndTime.Date &
                selectedDate.Date >= s.StartTime.Date
                )
                .ToList();

            return availableSittings;

        }

        [HttpGet("GetAvailableTimes/{sittingId}")]
        public IActionResult GetAvailableTimes(int sittingId, DateTime selectedDate)
        {
            try
            {
                var selectedSitting = _context.Sittings.FirstOrDefault(s => s.Id == sittingId);

                if (selectedSitting == null)
                {
                    return NotFound("Sitting not found");
                }

                // Calculate available times for the selected day (selectedDate)
                var midnight = selectedDate.TimeOfDay;
                TimeSpan quarterTo = new TimeSpan (23,59,0);
                var startTime = selectedSitting.StartTime.TimeOfDay;
                var endTime = selectedSitting.EndTime.TimeOfDay;
                var timeInterval = TimeSpan.FromMinutes(15); // Adjust as needed

                var availableTimes = new List<TimeSpan>();
                if (selectedSitting.StartTime.Date != selectedDate && selectedSitting.EndTime.Date > selectedDate)
                {
                    while (midnight <= quarterTo)
                    {
                        availableTimes.Add(midnight);
                        midnight = midnight.Add(timeInterval);
                    }
                }
                else if(selectedSitting.StartTime.Date != selectedDate && selectedSitting.EndTime.Date == selectedDate)
                {
                    while (midnight.Add(timeInterval) <= endTime)
                    {
                        availableTimes.Add(midnight);
                        midnight= midnight.Add(timeInterval);
                    }
                }
                else if(selectedSitting.StartTime.Date != selectedSitting.EndTime.Date)
                {
                    while(startTime <= quarterTo)
                    {
                        availableTimes.Add(startTime);
                        startTime = startTime.Add(timeInterval);
                    }
                }
                else
                {
                    while (startTime.Add(timeInterval) <= endTime)
                    {
                        availableTimes.Add(startTime);
                        startTime = startTime.Add(timeInterval);
                    }
                }

                return Ok(availableTimes);
            }
            catch (Exception ex)
            {
                return BadRequest("Error fetching available times: " + ex.Message);
            }
        }
        // Do we want to create more API endpoints, such as POST, PUT, DELETE for managing sittings?
    }

}

Major BeanScene ReservationSystem/Areas/Manager/Views/Sittings/Details.cshtml
@using System.Globalization;
@using Newtonsoft.Json;
@model Details

@{
    ViewData["Title"] = "Details";
}
<head>
    <link rel="stylesheet" href="~/css/bodyStylingForAllPages.css" />
    <style>
        .sittings-details{
            border: 2px solid #b27b43;
            border-radius:5px;
        }

        a {
            text-decoration:none;
        }

        a:hover {
            text-decoration:underline;
            color: #b27b43;
        }
    </style>
</head>

<div class="container-fluid d-flex flex-column min-vh-100">
    <div class="main-container flex-grow-1 bg-dark">
        <h4 class="text-center my-3"> @Model.Name Sitting Details</h4>
        <div class="container my-2">
            <div class="sittings-details m-2">
                <div class="row my-2 text-center">
                    <p class="col-md-6">
                        <strong>Sitting Id:</strong> @Model.Id
                    </p>
                    <p class="col-md-6">
                        <strong>Closed Sitting?:</strong> @Html.DisplayFor(model => model.IsClosed)
                    </p>
                </div>
                <div class="row my-2 text-center">
                    <p class="col-md-12">
                        <strong>Date/Time:</strong> @(Model.StartTime.ToString("dddd, d\" of \"MMMM h:mm tt") + " - " + Model.EndTime.ToString("dddd, d\" of \"MMMM h:mm tt"))
                    </p>
                </div>
                <div class="row my-2 text-center">
                    <p class="col-md-4">
                        <strong>Capacity:</strong> @Model.BookedGuest/@Model.Capacity
                    </p>   
                    <p class="col-md-4">
                        <strong>Restaurant:</strong> @Model.RestaurantNotAdapted.Name
                    </p>
                    <p class="col-md-4">
                        <strong>Sitting Type:</strong> @Model.SittingTypeNotAdapted.Name
                    </p>
                </div>
            </div>
        </div>
        <div class="text-center my-2">
            @{
                bool sittingInThePast = Model.EndTime < DateTime.Now;
            }
            <a class="@(sittingInThePast?"text-danger":"")" asp-area="Manager" asp-controller="Sittings" asp-route-id="@Model.Id" asp-action="Edit">Edit</a> |
            @* <a asp-action="Index">Back to List</a> | *@
            <a asp-controller="Home" asp-action="Calendar">Back to Calendar</a> |
            <a class="@(sittingInThePast?"text-danger":"")" asp-area="Manager" asp-controller="Sittings" asp-route-id="@Model.Id" asp-action="Delete">Delete</a>
        </div>
        <div>
            <h4 class="text-center">Reservations</h4>
            @if (DateTime.Now <= Model.EndTime)
            {
                <div class="text-center">
                    <a asp-area="Staff" asp-controller="Home" asp-route-chosenTime="@Model.StartTime.ToString("s")" asp-route-sittingId="@Model.Id" asp-action="Create">Make a reservation for this sitting</a>
                </div>


            }
            @if (TempData["Error"] != null)
            {
                <partial name="_ErrorMessage" />
            }
            @if (TempData["Success"] != null)
            {
                <partial name="_SuccessMessage" />
            }

            <hr />


            @if (!Model.ReservationsNotAdapted.Any())
            {
                <h4 class="text-center">No booked reservations</h4>
            }
            else
            {
                <div class="table-responsive m-2">
                    <table border="1" class="table" width="100%">
                        <thead>
                            <tr>
                                <td>First name</td>
                                <td>Last name</td>
                                <td>Email</td>
                                <td>Phone</td>
                                <td>Guest</td>
                                <td>Time</td>
                                <td>Origin</td>
                                <td>Status</td>
                                <td>Tables</td>
                                <td>Notes</td>
                                <td>Guest Info</td>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var u in Model.ReservationsNotAdapted)
                            {
                                <tr data-bs-toggle="modal" data-bs-target="#editModal" data-bs-resId="@u.Id" data-bs-pId="@u.Person.Id" data-bs-notes="@u.AdditionalNotes"
                            data-bs-guest="@(u.Guest != null ? $"{u.Guest.FirstName};{u.Guest.LastName};{u.Guest.Email};{u.Guest.PhoneNumber}" : "")"
                            data-bs-data="@($"{u.Id};{u.PersonId};{u.StartTime.ToString("s")};{u.SittingId};{u.Duration};{u.ReservationOrigin.Id};{u.ReservationStatus.Id}")">
                                    <td>@u.Person.FirstName</td>
                                    <td>@u.Person.LastName</td>
                                    <td>@u.Person.Email</td>
                                    <td>@u.Person.PhoneNumber</td>
                                    <td>@u.Guests</td>
                                    <td>@($"{u.StartTime.ToString("g")}  {u.Duration} (mins)")</td>
                                    <td>@u.ReservationOrigin.Name</td>
                                    <td>@u.ReservationStatus.Name</td>
                                    <td>
                                        @u.TablesToString
                                    </td>
                                    @if (u.AdditionalNotes == null)
                                    {
                                        <td class="text-danger">No additional notes</td>
                                    }
                                    else
                                    {
                                        <td>Click to see</td>
                                    }
                                    @if (u.Guest == null)
                                    {
                                        <td></td>
                                    }
                                    else
                                    {
                                        <td>@u.Guest.FullName</td>
                                    }
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>

            }
        </div>
    </div>
</div>



@await Html.PartialAsync("_EditReservationModal", Model.Reservation)
@section Scripts {
    <script src="~/js/ManagerSittingDetails.js"></script>
    <script>
        
        $("#delete").on("click",function (e){
            e.preventDefault();
            const id = $("#Id").val()
            $("#reservationForm").attr("action", "/Reservation/Delete").attr("asp-route", id)
            debugger;
            if (window.confirm("Are you sure you want to delete this reservation?")){
                $("#reservationForm").submit();
            }

        })
        $("#edit").on("click",function(e){
            e.preventDefault();
            const id = $("#Id").val()
            $("#reservationForm").attr("action","/Reservation/Edit").attr("asp-route",id)
            $("#reservationForm").submit()
        })

        
        //https://stackoverflow.com/questions/14375144/jquery-prevent-default-then-continue-default
                //https://stackoverflow.com/questions/26039603/process-a-form-submit-with-multiple-submit-buttons-in-javascript

        
    </script>
    
    @* <script>
        const callApi = (start) => {
            fetch(`/api/sittings/dateTime/${start}`)
                .then(response => {
                    if (!response.ok) {
                        throw new Error('Network response was not ok');
                    }
                    return response.json();
                })
                .then(data => {
                    $('#SittingId').empty();
                    if (data.length === 0) {
                        $('#SittingId').append($("<option/>").attr('value', '').text("No available sittings"));
                    } else {
                        $('#SittingId').append($("<option/>").attr('value', '').text(`${data.length} available sittings`));
                        $.each(data, function (index, item) {
                            $('#SittingId').append($("<option />").attr('value', item.id).text(item.name));
                        });
                    }
                })
                .catch(error => {
                    console.error("Error:", error);
                });
        }
        
        $("tr").click(function () {
            
            let currentTds = $(this).closest("tr").find("td"); // find all td of selected row
            let data = $(currentTds).parent().attr("data-bs-data")
            let splitData = data.split(';');
            let notes = $(currentTds).parent().attr("data-bs-notes");

            let firstName = $(currentTds).eq(0).text(); // eq= cell , text = inner text
            let lastName = $(currentTds).eq(1).text();
            let email = $(currentTds).eq(2).text();
            let phone = $(currentTds).eq(3).text();
            let guest = $(currentTds).eq(4).text();
   
            let start = splitData[0]
            let sitting = splitData[1]
            let duration = splitData[2]
            let origin = splitData[3]
            let status = splitData[4]

            $('#Reservation_FirstName').val(firstName)
            $('#Reservation_LastName').val(lastName)
            $('#Reservation_Email').val(email)
            $('#Reservation_PhoneNumber').val(phone)

            $('#StartTime').val(start)

            $('#SittingId').val(sitting)
            $('#Reservation_Duration').val(duration)
            $('#GuestsCount').val(guest)
            $('#OriginId').val(origin)
            $('#StatusId').val(status)
            $('#Reservation_AdditionalNotes').val(notes)

            //2023-09-01T07:30
            //Take a note of u.Start.ToString('s') and reconvert to ISO

            callApi(start);
            // fetch(`/api/sittings/dateTime/${start}`)
            // .then(response => {
            //     if (!response.ok) {
            //         throw new Error('Network response was not ok');
            //     }
            //     return response.json();
            // })
            // .then(data => {
            //     $('#SittingId').empty();
            //     if (data.length === 0) {
            //         $('#SittingId').append($("<option/>").attr('value', '').text("No available sittings"));
            //     } else {
            //         $('#SittingId').append($("<option/>").attr('value', '').text(`${data.length} available sittings`));
            //         $.each(data, function (index, item) {
            //             $('#SittingId').append($("<option />").attr('value', item.id).text(item.name));
            //         });
            //     }
            // })
            // .catch(error => {
            //     console.error("Error:", error);
            // });
            $('#StartTime').on("change", (function () {
                let selectedDate = $('#StartTime').val()

                callApi(selectedDate);
                // fetch(`/api/sittings/dateTime/${selectedDate}`)
                //     .then(response => {
                //         if (!response.ok) {
                //             throw new Error('Network response was not ok');
                //         }
                //         return response.json();
                //     })
                //     .then(data => {
                //         $('#SittingId').empty();
                //         if (data.length === 0) {
                //             $('#SittingId').append($("<option/>").attr('value', '').text("No available sittings"));
                //         } else {
                //             $('#SittingId').append($("<option/>").attr('value', '').text(`${data.length} available sittings`));
                //             $.each(data, function (index, item) {
                //                 $('#SittingId').append($("<option />").attr('value', item.id).text(item.name));
                //             });
                //         }
                //     })
                //     .catch(error => {
                //         console.error("Error:", error);
                //     });
            }));
                

        });
    </script> *@
    
}